### ISSUE TITLE
Creating QtCreator project files.

### ISSUE THREAD

**Issue by allenck** [ascii78/esp-template-qtcreator#1]
You have a great idea here. I think I've improved on your idea. see [ESP_Config](https://github.com/allenck/ESP_Config). I'd appreciate some feedback.

**Comment by ascii78** [comment]
Hi,

I should update this project, I'm now using native cmake for both qt creator and esp-idf, it's in master git and will be in 4.0, also in the stable releases now i think. Just follow https://docs.espressif.com/projects/esp-idf/en/latest/get-started-cmake/ and open resulting cmake CMakeLists.txt in QtCreator. Use idf.py to build/flash/monitor in another terminal.

**Comment by ascii78** [comment]
Forgot to close this, also marking this repo readonly since CMake is the way to go.
